// 本类型包用到的引擎与 Remotion 能力，集中从这里导入，方便整体替换。
export {
  Box,
  bodyStyle,
  Card,
  cardPadding,
  CodeMorph,
  CodePanel,
  codePanelHeight,
  ease,
  fitCodeFontSize,
  fontStack,
  headingStyle,
  monoStyle,
  rectStyle,
  SceneTitle,
  Slide,
  splitH,
  splitV,
  stackV,
  TextBlock,
  textWidth,
  useCueProgress,
  useCurrentIndex,
  useRevealFrames,
  useRevealProgress,
  useSceneText,
  useSlide,
  useTextFitGroup,
  useTitleLayout,
  withAlpha,
} from '../../engine';
export type { Rect, TextStyle, Theme } from '../../engine';
export { useCurrentFrame, useVideoConfig } from 'remotion';
