#!/usr/bin/env python3
"""
Spirit Forge — Phase 3: Forge (遣将)

Generate a working Claude Code SKILL.md from a persona-profile.json.
Reads the profile, applies skill-template.md, and produces a complete
skill directory with SKILL.md, references/, and supporting files.

Usage:
    python forge.py <persona-profile.json> [--skill-name <name>] [--output-dir <path>]
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# Allow running from skill root or scripts/ directory
_skill_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_skill_root))


# ---------------------------------------------------------------------------
# Main forge function
# ---------------------------------------------------------------------------

def forge(profile_path: str, skill_name: str = "", output_dir: Optional[str] = None) -> dict:
    """Generate a complete skill from a persona profile.

    Args:
        profile_path: Path to persona-profile.json
        skill_name: Desired skill identifier (auto-derived if empty)
        output_dir: Where to write the generated skill directory

    Returns:
        Summary dict with files created
    """
    profile = _load_profile(profile_path)
    if not profile:
        raise ValueError(f"Failed to load profile: {profile_path}")

    _print_header("Phase 3: Forge (遣将)")

    # Derive skill name
    if not skill_name:
        skill_name = _derive_skill_name(profile)
    print(f"  Skill name: {skill_name}")

    # Set up output directory
    if output_dir is None:
        output_dir = f".spirit-forge/{skill_name}/generated-skill"
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "references").mkdir(parents=True, exist_ok=True)

    files_created = []

    # ---- Generate SKILL.md ----
    print("  Generating SKILL.md ...")
    skill_md = _generate_skill_md(skill_name, profile)
    (out / "SKILL.md").write_text(skill_md, encoding="utf-8")
    files_created.append("SKILL.md")

    # ---- Generate reference files ----
    print("  Generating references/ ...")

    domain_knowledge = _generate_domain_knowledge(skill_name, profile)
    (out / "references" / "domain-knowledge.md").write_text(domain_knowledge, encoding="utf-8")
    files_created.append("references/domain-knowledge.md")

    comm_guide = _generate_communication_guide(skill_name, profile)
    (out / "references" / "communication-guide.md").write_text(comm_guide, encoding="utf-8")
    files_created.append("references/communication-guide.md")

    if profile.get("tools"):
        tool_prefs = _generate_tool_preferences(skill_name, profile)
        (out / "references" / "tool-preferences.md").write_text(tool_prefs, encoding="utf-8")
        files_created.append("references/tool-preferences.md")

    # ---- Generate .claude-plugin/plugin.json ----
    (out / ".claude-plugin").mkdir(parents=True, exist_ok=True)
    plugin_json = {
        "name": skill_name,
        "version": "0.1.0",
        "description": profile.get("persona_name", skill_name) + " emulation skill — generated by Spirit Forge",
        "author": {"name": "claude-uluo (via Spirit Forge)"},
        "keywords": [d["domain"] for d in profile.get("expertise", [])[:5]],
        "license": "MIT",
        "skills": "./",
    }
    with open(out / ".claude-plugin" / "plugin.json", "w") as f:
        json.dump(plugin_json, f, ensure_ascii=False, indent=2)
    files_created.append(".claude-plugin/plugin.json")

    summary = {
        "skill_name": skill_name,
        "output_dir": str(out),
        "files_created": files_created,
    }
    _print_footer(str(out), len(files_created))
    return summary


# ---------------------------------------------------------------------------
# SKILL.md generator
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Domain-aware workflow dispatch
# ---------------------------------------------------------------------------

WRITING_SIGNALS = {"writing", "essay", "author", "prose", "literature", "novel",
                    "poetry", "creative", "narrative", "composition", "rhetoric",
                    "创作", "写作", "文学", "散文", "小说", "诗歌"}
CODE_SIGNALS = {"python", "react", "javascript", "typescript", "rust", "go",
                "systems", "programming", "compiler", "api", "framework",
                "frontend", "backend", "devops", "infrastructure", "testing"}


def _detect_domain(profile: dict) -> str:
    domains = " ".join(d.get("domain", "").lower() for d in profile.get("expertise", []))
    if any(s in domains for s in WRITING_SIGNALS):
        return "writing"
    if any(s in domains for s in CODE_SIGNALS):
        return "code"
    return "generic"


def _generate_workflow(profile: dict) -> list[str]:
    domain = _detect_domain(profile)
    if domain == "writing":
        return _writer_workflow(profile)
    elif domain == "code":
        return _developer_workflow(profile)
    return _generic_workflow(profile)


def _writer_workflow(profile: dict) -> list[str]:
    persona = profile.get("persona_name", "this author")
    style = profile.get("style", {})
    return [
        "## How This Author Works",
        "",
        f"Channel {persona}'s creative process:",
        "",
        "1. **Opening**: How they start — " +
        ("weather/time setting, personal anecdote, or direct thesis" if style.get("phrases") else "observe their characteristic opening move"),
        "2. **Development**: How they build — " +
        ("layered scenes, argument through narrative, or recursive theme exploration" if style.get("explanation_style") else "follow their structural rhythm"),
        "3. **Voice**: Signature narrative techniques — " +
        ("first-person intrusion, dialect-marked dialogue, nature-as-symbolism" if style.get("formality", 5) < 5 else "detached observation, precise language, irony-as-distance"),
        "4. **Closure**: How they end — " +
        ("recursive return to opening image, declarative statement, or open-ended reflection"),
        "",
        "## Stylistic Rules (Never Break)",
        "",
        f"These are {persona}'s non-negotiable patterns. See [Gotchas](#gotchas) for details.",
        "",
    ]


def _developer_workflow(profile: dict) -> list[str]:
    expertise = profile.get("expertise", [])
    lines = [
        "## Workflow Protocol",
        "",
        "Approach technical problems systematically:",
        "",
    ]
    if expertise:
        lines.append("1. **Domain Assessment**: Identify which domains apply:")
        for exp in expertise[:5]:
            lines.append(f"   - {exp['domain']} (level: {exp['level']})")
        lines.append("")
    lines.extend([
        "2. **Pattern Matching**: Scan for established patterns before implementing",
        "3. **Gotcha Check**: Review [Gotchas](#gotchas) for relevant warnings",
        "4. **Decomposition**: Break into the smallest testable units",
        "5. **Verification**: Run through the gotcha checklist again after implementation",
        "",
    ])
    return lines


def _generic_workflow(profile: dict) -> list[str]:
    persona = profile.get("persona_name", "this person")
    expertise = profile.get("expertise", [])
    lines = [
        "## How This Person Works",
        "",
        f"Approach tasks the way {persona} would:",
        "",
    ]
    if expertise:
        lines.append("**Key domains:** " + ", ".join(d["domain"] for d in expertise[:5]))
        lines.append("")
    lines.extend([
        "1. **Assess**: Identify which domains and patterns apply",
        "2. **Check**: Review the [Gotchas](#gotchas) section for relevant warnings",
        "3. **Execute**: Apply the decision principles from Core Principles",
        "4. **Verify**: Confirm the output matches quality expectations",
        "",
    ])
    return lines


def _generate_skill_md(skill_name: str, profile: dict) -> str:
    """Generate the main SKILL.md content."""
    lines = []

    # ---- Frontmatter ----
    desc = _build_description(skill_name, profile)
    lines.extend([
        "---",
        f"name: {skill_name}",
        "description: >-",
    ])
    # Wrap description lines
    for line in desc.split("\n"):
        lines.append(f"  {line}")
    lines.extend([
        "---",
        "",
    ])

    # ---- Title ----
    persona_name = profile.get("persona_name", skill_name)
    lines.extend([
        f"# {skill_name}",
        "",
        f"Emulation of {persona_name}'s expertise, decision patterns, and professional style. "
        f"Generated by [Spirit Forge](https://github.com/YuluoY/claude-uluo) (拘灵遣将).",
        "",
        "## Core Principles",
        "",
    ])

    # ---- Principles (from heuristics, domain-aware format) ----
    domain = _detect_domain(profile)
    heuristics = profile.get("heuristics", [])
    for i, h in enumerate(heuristics[:8], 1):
        when = h.get("when", "")
        then = h.get("then", "")
        because = h.get("because", "")
        if domain == "writing":
            # Writers: "Rule: X" format
            if then:
                line = f"{i}. {then}"
                if because:
                    line += f" — {because}"
                lines.append(line)
        else:
            # Developers: "When X, prefer Y because Z" format
            parts = []
            if when:
                parts.append(f"When {when}")
            if then:
                parts.append(f"prefer {then}")
            if because:
                parts.append(f"because {because}")
            if parts:
                lines.append(f"{i}. {'; '.join(parts)}")
    if not heuristics:
        lines.append("*(Insufficient heuristics data — the distiller needs more source material)*")
    lines.append("")

    # ---- Workflow Protocol ----
    lines.extend([
        "## Workflow Protocol",
        "",
        f"Approach problems the way {persona_name} would:",
        "",
    ])

    # Build workflow from expertise domains — domain-aware dispatch
    expertise = profile.get("expertise", [])
    workflow = _generate_workflow(profile)
    lines.extend(workflow)
    lines.append("")

    # ---- Gotchas (HIGHEST SIGNAL section) ----
    lines.extend([
        "## Gotchas & Anti-Patterns",
        "",
        f"_These are patterns that {persona_name} consistently catches that others miss._",
        "",
    ])
    gotchas = profile.get("gotchas", [])
    if gotchas:
        for i, g in enumerate(gotchas[:15], 1):
            pattern = g.get("pattern", "")
            fix = g.get("fix", "")
            lines.append(f"### {i}. {pattern[:120]}")
            if fix:
                lines.append(f"**Fix**: {fix}")
            lines.append("")
    else:
        lines.append("*(Insufficient gotcha data — the distiller needs more source material)*")
        lines.append("")

    # ---- References ----
    lines.extend([
        "## Reference Files",
        "",
        "Progressive disclosure: detailed knowledge is in reference files.",
        "Load them only when the relevant domain arises.",
        "",
        "| File | When to Load |",
        "|------|-------------|",
        "| [domain-knowledge.md](references/domain-knowledge.md) | Deep diving into any expertise domain |",
        "| [communication-guide.md](references/communication-guide.md) | When output quality or tone matters |",
    ])
    if profile.get("tools"):
        lines.append("| [tool-preferences.md](references/tool-preferences.md) | When tool/IDE choices are relevant |")
    lines.append("")

    # ---- Communication Style (inline summary) ----
    style = profile.get("style", {})
    phrases = style.get("phrases", [])
    if phrases:
        lines.append("## Communication Style")
        lines.append(f"Formality: {style.get('formality', 5)}/10 | "
                     f"Explanation: {style.get('explanation_style', 'balanced')}")
        if phrases[:5]:
            lines.append(f"Signature markers: {'; '.join(phrases[:5])}")
        lines.append("")

    return "\n".join(lines)


def _build_description(skill_name: str, profile: dict) -> str:
    """Build the frontmatter description — written for the MODEL, not humans."""
    persona = profile.get("persona_name", skill_name)
    domains = [d["domain"] for d in profile.get("expertise", [])[:5]]
    domains_str = ", ".join(domains) if domains else "various domains"

    # Trigger phrases the model should recognize
    triggers = f"emulate {persona}, think like {persona}, "
    if domains:
        for d in domains[:3]:
            triggers += f"review {d} code, write {d}, debug {d}, "

    desc = (
        f"Emulates {persona}'s expertise in {domains_str}. "
        f"Use this skill when you need to {triggers}"
        f"or when the user asks to work in the style of {persona}. "
        f"Contains {len(profile.get('gotchas', []))} domain-specific gotchas "
        f"and {len(profile.get('heuristics', []))} decision heuristics extracted from "
        f"public writings and code patterns."
    )
    return desc


# ---------------------------------------------------------------------------
# Reference generators
# ---------------------------------------------------------------------------

def _generate_domain_knowledge(skill_name: str, profile: dict) -> str:
    lines = [f"# {skill_name} — Domain Knowledge", ""]
    for exp in profile.get("expertise", []):
        lines.append(f"## {exp['domain']} ({exp['level']})")
        lines.append("")
        evidence = exp.get("evidence", [])
        if evidence:
            for e in evidence[:5]:
                lines.append(f"- {e}")
        lines.append("")
    return "\n".join(lines)


def _generate_communication_guide(skill_name: str, profile: dict) -> str:
    style = profile.get("style", {})
    lines = [
        f"# {skill_name} — Communication Guide",
        "",
        f"**Formality**: {style.get('formality', 5)}/10",
        f"**Explanation Style**: {style.get('explanation_style', 'balanced')}",
        "",
        "## Signature Phrases",
    ]
    for p in style.get("phrases", []):
        lines.append(f"- {p}")
    lines.append("")
    lines.append("## Sentence Patterns")
    for p in style.get("patterns", []):
        lines.append(f"- {p}")
    return "\n".join(lines)


def _generate_tool_preferences(skill_name: str, profile: dict) -> str:
    lines = [f"# {skill_name} — Tool Preferences", ""]
    for tool in profile.get("tools", []):
        lines.append(f"- **{tool['name']}**: {tool.get('usage', '')}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_profile(path: str) -> Optional[dict]:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Profile not found: {path}")
    return json.loads(p.read_text(encoding="utf-8"))


def _derive_skill_name(profile: dict) -> str:
    """Derive a kebab-case skill name from persona info."""
    name = profile.get("persona_name", "unknown")
    name = name.lower().replace(" ", "-").replace("@", "").replace("/", "-")
    name = re.sub(r'[^a-z0-9-]', '', name)
    name = re.sub(r'-+', '-', name)  # Collapse multiple hyphens
    domains = [d["domain"].lower().replace(" ", "-") for d in profile.get("expertise", [])[:2]]
    if domains:
        name = f"{name}-{'-'.join(domains)}"
    return name[:50]


def _print_header(title: str):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")


def _print_footer(output_dir: str, file_count: int):
    print(f"\n{'='*60}")
    print(f"  Skill written to: {output_dir}")
    print(f"  Files created: {file_count}")
    print(f"{'='*60}\n")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Spirit Forge — Forge (遣将): Generate SKILL.md from persona profile"
    )
    parser.add_argument("profile", help="Path to persona-profile.json")
    parser.add_argument("--skill-name", default="", help="Desired skill identifier")
    parser.add_argument("--output-dir", default=None, help="Output directory for generated skill")
    args = parser.parse_args()

    summary = forge(args.profile, args.skill_name, args.output_dir)
